{% set name = "google-cloud-container" %}
{% set version = "2.28.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/google-cloud-container-{{ version }}.tar.gz
  sha256: c8c2fcedb096b2e895fa37339eee900da2f02b14826f835dd81526e5ffb0b511

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7,<3.11
    - pip
  run:
    - python >=3.7,<3.11
    - google-api-core-grpc >=1.34.0,<3.0.0dev,!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,!=2.10.*
    - proto-plus >=1.22.0,<2.0.0dev
    - protobuf >=3.19.5,<5.0.0dev,!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5

test:
  imports:
    - google.cloud.container
    - google.cloud.container_v1
    - google.cloud.container_v1beta1
    - grpc
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/googleapis/python-container
  summary: Google Cloud Container API client library
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  description: |
    **Python Client for Google Kubernetes Engine API**

    [Google Kubernetes Engine API](https://cloud.google.com/kubernetes-engine): The Google Kubernetes Engine API is used for
    building and managing container based applications, powered by the open source
    Kubernetes technology.

    - [Client Library Documentation](https://googleapis.dev/python/container/latest/index.html)
    - [Product Documentation](https://cloud.google.com/kubernetes-engine)

    **Quick Start**

    In order to use this library, you first need to go through the following steps:

    1. [Select or create a Cloud Platform project.](https://console.cloud.google.com/project)
    2. [Enable billing for your project.](https://cloud.google.com/billing/docs/how-to/modify-project#enable_billing_for_a_project)
    3. [Enable the Google Cloud Language API.](https://cloud.google.com/natural-language)
    4. [Setup Authentication.](https://googleapis.github.io/google-cloud-python/latest/core/auth.html)

    **Supported Python Versions**

    Python >= 3.5

    **Deprecated Python Versions**

    Python == 2.7
    - Python 2.7 support will be removed on January 1, 2020.
    - protobuf does not support Visual C++ 2008, windows py27 package not available

  doc_url: https://googleapis.dev/python/container/latest/index.html
  dev_url: https://github.com/googleapis/python-container

extra:
  recipe-maintainers:
    - xylar
    - BrentDorsey
    - parthea
