{% set name = "google-cloud-container" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 566834ef43e79917b112e3bd2848e84cfb0f4d7b565581607e2548f5c8e5d87a

build:
  number: 2
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --verbose"

requirements:
  host:
    - python
    - pip >=18.1
    - google-api-core-grpc >=1.6.0
    - enum34 >=1.1.6  # [py2k]
    - futures >=3.0.5  # [py2k]
  run:
    - python
    - google-api-core-grpc
    - enum34  # [py2k]
    - futures  # [py2k]

test:
  imports:
    - enum
    - google.api
    - google.api.annotations_pb2
    - google.api.http_pb2
    - google.api_core.gapic_v1.client_info
    - google.api_core.gapic_v1.config
    - google.api_core.gapic_v1.method
    - google.api_core.grpc_helpers
    - google.api_core.protobuf_helpers
    - google.cloud
    - google.cloud.container_v1
    - google.cloud.container_v1.proto
    - google.oauth2
    - google.oauth2.service_account
    - google.protobuf
    - google.protobuf.empty_pb2
    - grpc
    - requests

about:
  home: https://github.com/googleapis/google-cloud-python/tree/master/container
  license: Apache 2.0
  license_family: APACHE
  summary: 'Google Container Engine API client library'
  description: |
    **Python Client for Google Kubernetes Engine API**

    [Google Kubernetes Engine API](https://cloud.google.com/kubernetes-engine): The Google Kubernetes Engine API is used for
    building and managing container based applications, powered by the open source
    Kubernetes technology.

    - [Client Library Documentation](https://googleapis.github.io/google-cloud-python/latest/container/index.html)
    - [Product Documentation](https://cloud.google.com/kubernetes-engine)

    **Quick Start**

    In order to use this library, you first need to go through the following steps:

    1. [Select or create a Cloud Platform project.](https://console.cloud.google.com/project)
    2. [Enable billing for your project.](https://cloud.google.com/billing/docs/how-to/modify-project#enable_billing_for_a_project)
    3. [Enable the Google Cloud Language API.](https://cloud.google.com/natural-language)
    4. [Setup Authentication.](https://googleapis.github.io/google-cloud-python/latest/core/auth.html)

    **Supported Python Versions**

    Python >= 3.5

    **Deprecated Python Versions**

    Python == 2.7. Python 2.7 support will be removed on January 1, 2020.

  doc_url: https://googleapis.github.io/google-cloud-python/latest/container/index.html
  dev_url: https://github.com/googleapis/google-cloud-python/tree/master/container

extra:
  recipe-maintainers:
    - BrentDorsey
